apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-deployment
  labels:
    app: eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop
  template:
    metadata:
      labels:
        app: eshop
    spec:
      containers:
      - name: legacywebshop
        image: mavogel/hska-vis-legacywebshop
        ports:
        - containerPort: 8888
        labels:
          app: legacywebshop
      - name: web-shop-db-image
        image: mavogel/hska-vis-web-shop-db-image
        volumeMounts:
        - name: mysql-pv
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
        labels:
          app: database
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            mysql-secret:
              name: root-password
              key: root-password
        - name: MYSQL_DATABASE
          valueFrom:
            mysql-config:
              name: database
              key: database
        - name: MYSQL_USER
          valueFrom:
            mysql-config:
              name: user
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            mysql-secret:
              name: password
              key: password
      - name: product
        image: product
        ports:
        - containerPort: 8082
        labels:
          app: product
      - name: category
        image: category
        ports:
        - containerPort: 8081
        labels:
          app: category
      volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-claim
