version: '3.2'
services:
  legacywebshop:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8080"
    networks:
      local_dev_net:
          aliases:
              - legacywebshop

  web-shop-db-image:
    build:
      context: ./
      dockerfile: ./docker/DockerfileMySQL
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image
  category-service:
    image: category-service
    ports:
      - "8081:8081"
    environment:
      MYSQL_ADDRESS: "web-shop-db-image:3306"
      MYSQL_USER: categoryuser
      MYSQL_PASSWORD: categoryuser
      MYSQL_DATABASE: Categories
    networks:
      local_dev_net:
        aliases:
          - category-service
  product-service:
    image: product-service
    ports: 
      - "8082:8082"
    environment:
      MYSQL_ADDRESS: "web-shop-db-image:3306"
      MYSQL_USER: productuser
      MYSQL_PASSWORD: productuser
      MYSQL_DATABASE: Products
    networks:
      local_dev_net:
        aliases:
          - product-service

networks:
  local_dev_net:
    driver: bridge
