version: '3.2'
services:
  legacywebshop:
    image: mavogel/hska-vis-legacywebshop
    ports:
      - "8888:8080"
    networks:
      local_dev_net:
          aliases:
              - legacywebshop

  web-shop-db-image:
    image: mavogel/hska-vis-web-shop-db-image
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image
  category-service:
    image: category-service
    ports:
      - "8081:8080"
    environment:
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    networks:
      local_dev_net:
        aliases:
          - category-service
  product-service:
    image: product-service
    ports: 
      - "8082:8080"
    environment:
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    networks:
      local_dev_net:
        aliases:
          - product-service



networks:
  local_dev_net:
    driver: bridge
