apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: YzhkZTExMGYzNzMwMGE1M2E5NzE3NDk=
  webshop-password: d2Vic2hvcHVzZXI=
  category-password: Y2F0ZWdvcnl1c2Vy
  product-password: cHJvZHVjdHVzZXI=