apiVersion: v1
kind: Service
metadata:
  name: legacy-service
spec:
  type: NodePort
  selector:
    app: legacywebshop
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8080
    nodePort: 30011